# Site settings
title: countless-integers blog
description: > 
    My random thoughts and weird stories inspired by daily coding. 
    This blog runs on the awesome Jekyll.
baseurl: "" 
url: "https://countless-integers.github.io" 
#twitter_username: 
github_username:  countless-integers
google_analytics: "UA-67251979-1"

# Build settings
markdown: kramdown
