# Site settings
title: countless-integers blog
#email: totcha@gazeta.pl 
description: > # this means to ignore newlines until "baseurl:"
    My random thoughts and weird stories inspired by dailly coding. 
    This blog runs on the awesome Jekyl.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://countless-integers.github.io" # the base hostname & protocol for your site
#twitter_username: 
github_username:  countless-integers
google_analytics: "UA-67251979-1"

# Build settings
markdown: kramdown
